name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # ÙƒÙ„ 12 Ø³Ø§Ø¹Ø©
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write   # ğŸ‘ˆ ØªØ³Ù…Ø­ Ù„Ù„Ù€ workflow ÙŠÙƒØªØ¨ ÙÙŠ Ø§Ù„Ø±ÙŠØ¨Ùˆ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake animations
        uses: Platane/snk@v3
        with:
          github_user_name: Hedra-Nabil
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light
            dist/snake-color.svg?color_snake=#ff6b6b&color_dots=#628fdb,#8bc34a,#ffc107,#e91e63

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
